displayName=Level Requirements
author=Harry Styles
description=Displays a skill icon + Level requirements on everything associated with level requirements in the game to save time looking at the wiki.
tags=level, requirements, level requirements, reqs, req, skill, skill level, skill reqs, skill req, level, levels, harry styles
version=0.0.1
plugins=com.harrystyles.levelreqs.LevelRequirementsPlugin
build=standard